---
name: KBase SDK Tests

on:
  pull_request:
    branches:
      - master
      - main
      - develop
  push:
    branches:
      - master
      - main

jobs:
  sdk_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out GitHub repo
        uses: actions/checkout@v2
      - name: Check out Actions CI files
        uses: actions/checkout@v2
        with:
          repository: 'kbaseapps/kb_sdk_actions'
          path: 'kb_sdk_actions'
      - name: Check file existence
        id: check_files
        uses: andstor/file-existence-action@v1
        with:
          files: kbase.yml
      - name: Set up test environment
        if: steps.check_files.outputs.files_exists == 'true'
        shell: bash
        env:
          KBASE_TEST_TOKEN: ${{ secrets.KBASE_TEST_TOKEN }}
        run: |
          # Verify kb_sdk_actions clone worked
          test -f "$HOME/kb_sdk_actions/bin/kb-sdk" && echo "CI files cloned"
          docker pull "kbase/kb-sdk:/latest"
          sh $GITHUB_WORKSPACE/kb_sdk_actions/bin/make_testdir \
          && echo "Created test_local"
          test -f "test_local/test.cfg" && echo "Confirmed config exists"
      - name: Configure authentication
        if: steps.check_files.outputs.files_exists == 'true'
        shell: bash
        env:
          KBASE_TEST_TOKEN: ${{ secrets.KBASE_TEST_TOKEN }}
        run: |
          # Add token to config
          sed -ie "s/^test_token=.*$/&$KBASE_TEST_TOKEN/g" ./test_local/test.cfg
      - name: Run tests
        if: steps.check_files.outputs.files_exists == 'true'
        shell: bash
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        run: |
          sh kb-sdk test
          bash <(curl -s https://codecov.io/bash)
